FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=devops

# Create a database and user
ENV MYSQL_DATABASE=devops
ENV MYSQL_USER=devops
ENV MYSQL_PASSWORD=devops

# Add the content of the sql-scripts/ directory to your image


# Expose the port the app runs on
EXPOSE 3306